# Generated by Django 5.1.1 on 2025-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
