# Generated by Django 5.1.1 on 2025-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_proposal_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
