# Generated by Django 5.1.1 on 2025-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_alter_proposal_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
