# Generated by Django 5.1.1 on 2025-02-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('is_foreigner', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_illiterate', models.CharField(blank=True, max_length=10, null=True)),
                ('rg', models.CharField(max_length=100)),
                ('rg_public_agency', models.CharField(max_length=20)),
                ('rg_uf', models.CharField(max_length=20)),
                ('rg_created_date', models.DateField()),
                ('naturality_city', models.CharField(max_length=50)),
                ('naturality_uf', models.CharField(max_length=20)),
                ('father', models.CharField(max_length=200)),
                ('mother', models.CharField(max_length=200)),
                ('telphone', models.CharField(max_length=15)),
                ('celphone', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('city_state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('complement', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('agency_id', models.IntegerField()),
                ('agency', models.CharField(max_length=10)),
                ('agency_code', models.CharField(max_length=200)),
                ('agency_uf', models.CharField(max_length=20)),
                ('agency_is_cm', models.CharField(max_length=3)),
                ('income', models.FloatField()),
                ('account_type', models.CharField(max_length=10)),
                ('account_bank', models.CharField(max_length=200)),
                ('account_agency', models.IntegerField()),
                ('account', models.IntegerField()),
                ('account_dv', models.IntegerField()),
                ('is_representated', models.CharField(default='NÃO', max_length=10)),
                ('rep_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rep_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
