from .models import Proposal
from django import forms

UF_CHOICES = [
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AM', 'Amazonas'),
    ('AP', 'Amapá'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MG', 'Minas Gerais'),
    ('MS', 'Mato Grosso do Sul'),
    ('MT', 'Mato Grosso'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('PR', 'Paraná'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('RS', 'Rio Grande do Sul'),
    ('SC', 'Santa Catarina'),
    ('SE', 'Sergipe'),
    ('SP', 'São Paulo'),
    ('TO', 'Tocantins')
]


BANK_OPTIONS = [
    ("001", "001 - BANCO DO BRASIL"),
    ("003", "003 - BANCO DA AMAZÔNIA"),
    ("004", "004 - BANCO DO NORDESTE DO BRASIL"),
    ("012", "012 - BANCO INBURSA S.A."),
    ("021", "021 - BANCO BANESTES"),
    ("025", "025 - BANCO ALFA"),
    ("026", "026 - BANCO DO ESTADO DO ACRE S.A."),
    ("028", "028 - BANCO BANEB"),
    ("029", "029 - BANCO ITAÚ CONSIGNADO"),
    ("033", "033 - BANCO SANTANDER"),
    ("035", "035 - BANCO DO ESTADO DO CEARÁ"),
    ("037", "037 - BANCO DO ESTADO DO PARÁ"),
    ("038", "038 - BANCO BANESTADO"),
    ("039", "039 - BANCO DO ESTADO DO PIAUÍ"),
    ("041", "041 - BANCO BANRISUL"),
    ("047", "047 - BANCO DO ESTADO DE SERGIPE"),
    ("063", "063 - BANCO IBI"),
    ("069", "069 - BANCO CREFISA"),
    ("070", "070 - BANCO BRB"),
    ("077", "077 - BANCO INTER"),
    ("081", "081 - BANCO SEGURO SA"),
    ("104", "104 - BANCO CAIXA ECONÔMICA FEDERAL"),
    ("121", "121 - BANCO AGIBANK"),
    ("122", "122 - BANCO BANERJ COMPE"),
    ("134", "134 - BANCO CAPEMISA"),
    ("149", "149 - FACTA FINANCEIRA S.A - CRÉDITO FINANCIAMENTO E INVESTIMENTO"),
    ("169", "169 - BANCO OLÉ BONSUCESSO CONSIGNADO S.A."),
    ("218", "218 - BANCO OLÉ CONSIGNADO"),
    ("229", "229 - BANCO CRUZEIRO DO SUL"),
    ("233", "233 - BANCO CIFRA"),
    ("237", "237 - BANCO BRADESCO"),
    ("241", "241 - BANCO CLÁSSICO"),
    ("243", "243 - BANCO MASTER"),
    ("250", "250 - BANCO BCV"),
    ("254", "254 - BANCO PARANÁ"),
    ("260", "260 - NUBANK"),
    ("263", "263 - BANCO CACIQUE"),
    ("290", "290 - BANCO PAGBANK"),
    ("290", "290 - BANCO PAGSEGURO"),
    ("318", "318 - BANCO BMG"),
    ("321", "321 - CCB BRASIL S.A"),
    ("323", "323 - MERCADO PAGO"),
    ("329", "329 - QI SOCIEDADE DE CRÉDITO DIREITO S.A"),
    ("330", "330 - BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A."),
    ("336", "336 - BANCO C6 BANK"),
    ("341", "341 - BANCO ITAÚ"),
    ("348", "348 - BANCO XP"),
    ("359", "359 - FINANCEIRA ZEMA"),
    ("377", "377 - BANCO BMS"),
    ("380", "380 - PICPAY SERVIÇOS S.A."),
    ("394", "394 - BANCO BRADESCO FINANCIAMENTOS"),
    ("399", "399 - BANCO HSBC"),
    ("412", "412 - BANCO CAPITAL"),
    ("413", "413 - BANCO BV S.A."),
    ("422", "422 - BANCO SAFRA"),
    ("426", "426 - CCB BRASIL (BIC)"),
    ("432", "432 - CCB BRASIL FINANCEIRA (SUL FINANCEIRA)"),
    ("456", "456 - DAYCOVAL - CRÉDITO PESSOAL"),
    ("536", "536 - BANCO NEON"),
    ("593", "593 - BANCO DO ESTADO DO MARANHÃO"),
    ("595", "595 - BANCO NBC BANK"),
    ("600", "600 - BANCO DO EST DO RIO GR DO SUL"),
    ("611", "611 - BANCO PAULISTA"),
    ("623", "623 - BANCO PAN"),
    ("626", "626 - BANCO FICSA"),
    ("636", "636 - BANCO SOFISA"),
    ("643", "643 - BANCO PINE"),
    ("654", "654 - BANCO DIGIMAIS"),
    ("655", "655 - BANCO VOTORANTIM"),
    ("707", "707 - BANCO DAYCOVAL"),
    ("739", "739 - BANCO BCN"),
    ("740", "740 - BANCO BCN"),
    ("745", "745 - BANCO CITIBANK"),
    ("752", "752 - BNP PARIBAS BRASIL S.A."),
    ("756", "756 - BANCO COOPERATIVO DO BRASIL"),
    ("748", "748 - BANCO COOPERATIVO SICREDI"),
    ("756", "756 - SICOOB"),
    ("905", "905 - ALFA FINANCEIRA"),
    ("908", "908 - PARATI - CREDITO, FINANCIAMENTO E INVESTIMENTO"),
    ("917", "917 - BANCO BARIGUI (SOCICRED)"),
    ("921", "921 - CREDIFAR S.A."),
    ("925", "925 - BRB - CRÉDITO, FINANCIAMENTO E INVESTIMENTO"),
    ("935", "935 - FACTA FINANCEIRA (INSS)"),
    ("966", "966 - BANCO SABEMI"),
    ("9999", "9999 - OUTROS"),
]


STATUS_CHOICES = [
    ('1', 'Aberto'),
    ('2', 'Aguardando Digitação'),
    ('3', 'Pendente Pré-digitação'),
    ('4', 'Pendente Formalização'),
    ('5', 'Aguardando Averbação'),
    ('6', 'Aguardando retorno CIP'),
    ('7', 'Pendente envio CIP'),
    ('8', 'Saldo Informado Aguardando Pagamento'),
    ('9', 'Saldo Informado Aguardando Atuação do Operacional'),
    ('10', 'Pendente CIP'),
    ('11', 'Pago'),
    ('12', 'Pagamento Devolvido'),
    ('13', 'Comissão Processada'),
    ('14', 'Cancelado'),
]


FORM_TYPE_CHOICES = [
    ('físico', "Físico"),
    ('digital', "Digital")
]


class ProposalForm(forms.ModelForm):

    class Meta:
        model = Proposal
        fields = '__all__'


class ProposalForm(forms.ModelForm):
    class Meta:
        model = Proposal
        fields = [
            'name',
            'cpf',
            'birthdate',
            'sex',
            'is_foreigner',
            'email',
            'is_illiterate',
            'rg',
            'rg_public_agency',
            'rg_uf',
            'rg_created_date',
            'naturality_city',
            'naturality_uf',
            'father',
            'mother',
            'telphone',
            'celphone',
            'postal_code',
            'city',
            'city_state',
            'district',
            'place',
            'complement',
            'house_number',
            'agency_id',
            'agency',
            'agency_code',
            'agency_uf',
            'agency_is_cm',
            'income',
            'account_type',
            'account_bank',
            'account_agency',
            'account',
            'account_dv',
            'is_representated',
            'rep_cpf',
            'rep_name',
            'ade',
            'is_blocked',
            'internal_code',
            'user',
            'installment',
            'ballance',
            'total_amount',
            'exchange',
            'term',
            'term_paids',
            'term_original',
            'contract',
            'original_bank',
            'observation',
        ]

        widgets = {
            'ade': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '50'}),
            'is_blocked': forms.CheckboxInput(attrs={'class': 'form-control form-control-sm'}),
            'internal_code': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'user': forms.Select(attrs={'class': 'form-control form-control-sm input-disabled'}),
            'table': forms.Select(attrs={'class': '  input-disabled'}),
            'installment': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '7'}),
            'ballance': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'total_amount': forms.NumberInput(attrs={'class': 'form-control form-control-sm input-disabled'}),
            'exchange': forms.NumberInput(attrs={'class': 'form-control form-control-sm input-disabled'}),
            'term': forms.NumberInput(attrs={'class': 'form-control form-control-sm input-disabled'}),
            'term_paids': forms.NumberInput(attrs={'class': 'form-control form-control-sm input-disabled'}),
            'term_original': forms.NumberInput(attrs={'class': 'form-control form-control-sm input-disabled'}),
            'contract': forms.TextInput(attrs={'class': 'form-control form-control-sm input-disabled', 'maxlength': '200'}),
            'original_bank': forms.Select(choices=BANK_OPTIONS, attrs={'class': 'form-control form-control-sm input-disabled', 'maxlength': '200'}),
            'observation': forms.Textarea(attrs={'class': 'form-control form-control-sm'}),
            'status': forms.Select(attrs={'class': 'form-control form-control-sm'}),
            'name': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '11'}),
            'birthdate': forms.DateInput(attrs={'class': 'form-control form-control-sm', 'type': 'date'}),
            'sex': forms.Select(attrs={'class': 'form-control form-control-sm'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-sm'}),
            'rg': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
            'rg_public_agency': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '20'}),
            'rg_uf': forms.Select(choices=UF_CHOICES, attrs={'class': 'form-control form-control-sm'}),
            'rg_created_date': forms.DateInput(attrs={'class': 'form-control form-control-sm', 'type': 'date'}),
            'naturality_city': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '50'}),
            'naturality_uf': forms.Select(choices=UF_CHOICES, attrs={'class': 'form-control form-control-sm'}),
            'father': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'mother': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'telphone': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '15'}),
            'celphone': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '15'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '10'}),
            'city': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'city_state': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '20'}),
            'district': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'place': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'complement': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
            'house_number': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '20'}),
            'agency_id': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'agency': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '10'}),
            'agency_code': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'agency_uf': forms.Select(choices=UF_CHOICES, attrs={'class': 'form-control form-control-sm'}),
            'agency_is_cm': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '3'}),
            'income': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'account_type': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '10'}),
            'account_bank': forms.Select(choices=BANK_OPTIONS, attrs={'class': 'form-control form-control-sm', 'maxlength': '200'}),
            'account_agency': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'account': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'account_dv': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'last_update': forms.DateTimeInput(attrs={'class': 'form-control form-control-sm', 'type': 'datetime-local'}),
            'status': forms.Select(choices=STATUS_CHOICES, attrs={'class': 'form-control form-control-sm input-disabled'}),
            'form_type': forms.Select(choices=STATUS_CHOICES, attrs={'class': 'form-control form-control-sm input-disabled'}),
        }
