# Generated by Django 5.1.1 on 2025-02-12 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment', models.FloatField(blank=True, null=True)),
                ('bank_destiny', models.CharField(blank=True, max_length=100, null=True)),
                ('ballance', models.FloatField(blank=True, null=True)),
                ('exchange', models.FloatField(blank=True, null=True)),
                ('term', models.IntegerField(blank=True, null=True)),
                ('term_paids', models.IntegerField(blank=True, null=True)),
                ('term_original', models.IntegerField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=200, null=True)),
                ('original_bank', models.CharField(blank=True, max_length=200, null=True)),
                ('operation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('cpf', models.CharField(max_length=14)),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('aguardando', 'Aguardando'), ('finalizada', 'Finalizada')], default='aberto', max_length=50)),
                ('installment', models.ManyToManyField(blank=True, related_name='installment_simulation', to='simulation.installment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
