# Generated by Django 5.1.1 on 2025-02-01 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateField()),
                ('production', models.FloatField()),
                ('bonification', models.FloatField(blank=True, null=True)),
                ('total_comission', models.FloatField(blank=True, null=True)),
                ('deduction', models.FloatField()),
                ('comission', models.FloatField()),
                ('proposals', models.ManyToManyField(blank=True, related_name='dispatches', to='proposal.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
