# Generated by Django 5.1.1 on 2025-02-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateField()),
                ('production', models.FloatField()),
                ('bonification', models.FloatField(blank=True, null=True)),
                ('total_comission', models.FloatField(blank=True, null=True)),
                ('deduction', models.FloatField()),
                ('comission', models.FloatField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago'), ('enviado para pagamento', 'Enviado Para Pagamento'), ('aguarda financeiro', 'Aguarda Financeiro'), ('aguardando físico', 'Aguardando Físico')], default='aberto', max_length=200)),
            ],
        ),
    ]
