# Generated by Django 5.1.1 on 2025-02-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cms_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
