# Generated by Django 5.1.1 on 2025-02-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coefficient', models.CharField(default='0', max_length=20)),
                ('rate', models.FloatField()),
                ('term', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cms', models.CharField(default='0', max_length=20)),
                ('cms_type', models.CharField(choices=[('bruto', 'Bruto'), ('liquido', 'Líquido')], default='liquido', max_length=200)),
                ('type', models.CharField(choices=[('físico', 'Físico'), ('digital', 'Digital')], default='digital', max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation', to='bank.bank')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation', to='operation.operation')),
            ],
        ),
    ]
